### ISSUE TITLE
Performance improvement by removing WaitUntilReady from individual operation

### ISSUE THREAD

**Issue by Amar-C** [thotasrinath/xk6-couchbase#14]
Hi,

Looks like `WaitUntilReady` is called from individual operations. Do we need to call it before every operation? Can we just call it during initial connection setup? If we remove this from individual operation, we can gain ~15% more performance from this plugin (internal testing results)

**Comment by thotasrinath** [comment]
Thanks for the findings @Amar-C, I will make it optional.

**Comment by sharathjag** [comment]
Hi @thotasrinath 
I work with @Amar-C and can contribute towards this issue. Do you have few minutes to discuss how you want us to proceed? Let me know what time/timezone works for you.

**Comment by thotasrinath** [comment]
Hi @sharathjag, I am comfortable with SG timezone. Let me know when you would like to connect.

**Comment by sharathjag** [comment]
Thanks @thotasrinath I will send an invite your way. Is there a way to reach out to you?

Also opened: https://github.com/thotasrinath/xk6-couchbase/pull/17
Happy to discuss that as well when we sync.

**Comment by thotasrinath** [comment]
Thanks, I can connect through teams. Please send me an invite on Srinath.thota@outlook.com

**Comment by Amar-C** [comment]
@thotasrinath As the PR is merged can you help create a new release for it?

**Comment by thotasrinath** [comment]
Sure @Amar-C, Can help to update readme according to the changes please.

**Comment by Amar-C** [comment]
> Sure @Amar-C, Can help to update readme according to the changes please.

Yup, Sharath updated the README. Could you please create a new tag? I can do it but not sure which CPU are you building the binary for?

**Comment by thotasrinath** [comment]
Please go ahead and create. I am at my home town with limited access.

Thanks,
Srinath
________________________________

**Comment by Amar-C** [comment]
https://github.com/thotasrinath/xk6-couchbase/releases/tag/v0.0.9 should have the improvements
