### ISSUE TITLE
Installation Instructions ?

### ISSUE THREAD

**Issue by zx8086** [thotasrinath/xk6-couchbase#5]
How to install and why is this not part of the Grafana Labd xk6 repos like such ?

github.com/grafana/xk6-couchbase@latest

`2024/03/24 11:31:40 [INFO] Initializing Go module
2024/03/24 11:31:40 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init k6 
go: creating new go.mod: module k6
2024/03/24 11:31:40 [INFO] Pinning versions
2024/03/24 11:31:40 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod edit -require github.com/thotasrinath/xk6-couchbase@latest 
2024/03/24 11:31:40 [INFO] exec (timeout=0s): /usr/local/go/bin/go mod tidy -compat=1.17 
go: downloading github.com/thotasrinath/xk6-couchbase v0.0.4
go: k6 imports
        github.com/thotasrinath/xk6-couchbase: github.com/thotasrinath/xk6-couchbase@v0.0.4: verifying module: checksum mismatch
        downloaded: h1:E+eNWQByFW1ffQhcVvP5c5GZIzI3DGlSv5g/PKDm6sY=
        sum.golang.org: h1:UX49IbV9IMip/0KG3ilXM1LMruj7GceZZ7JIaaua/uI=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.`

**Comment by thotasrinath** [comment]
Have made the installation instructions. Thanks
